# Generated by Django 3.2.11 on 2022-01-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_diet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='diet',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Рацион'),
        ),
    ]
