# Generated by Django 3.2.11 on 2022-01-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_diet_diet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveSmallIntegerField(verbose_name='Количество дней')),
                ('type', models.BooleanField(default=True, verbose_name='Тип')),
                ('diet', models.PositiveSmallIntegerField(default=0, verbose_name='Рацион')),
            ],
        ),
    ]
